[[constraint]]
  name = "github.com/abbot/go-http-auth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/djherbis/atime"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
